[package]
name = "vm-proc"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.27", features = ["full"] }
quote = "1.0.32"

[features]
default = []
enabled = []